# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

producteur_produit_add:
    path: /producteur/produit/add
    controller: App\Controller\ProducteurProduitController::add

producteur_produit_edit:
    path: /producteur/produit/{id}/edit
    controller: App\Controller\ProducteurProduitController::edit

producteur_produit_delete:
    path: /producteur/produit/{id}/delete
    controller: App\Controller\ProducteurProduitController::delete

si_edit_user:
    path: /SI/{id}/edit
    controller: App\Controller\SIDashboardController::editerAdmin